-- VALTRAIN / Supabase schema
-- Run this whole file in Supabase -> SQL Editor.

create table if not exists public.trainings (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.exercises (
  id text primary key,
  training_id text not null references public.trainings(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null default '',
  weapon text not null default '',
  result_type text not null default 'time',
  unit text not null default 'сек',
  goal text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.results (
  id bigint generated by default as identity primary key,
  exercise_id text not null references public.exercises(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  result_date timestamptz not null default now(),
  value text,
  value_a text,
  value_b text,
  placement text,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_completions (
  exercise_id text not null references public.exercises(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  completion_date date not null,
  primary key (exercise_id, completion_date)
);

create index if not exists trainings_user_idx on public.trainings(user_id, sort_order);
create index if not exists exercises_training_idx on public.exercises(training_id, sort_order);
create index if not exists results_exercise_date_idx on public.results(exercise_id, result_date);
create index if not exists daily_user_date_idx on public.daily_completions(user_id, completion_date);

alter table public.trainings enable row level security;
alter table public.exercises enable row level security;
alter table public.results enable row level security;
alter table public.daily_completions enable row level security;

drop policy if exists "Users manage own trainings" on public.trainings;
create policy "Users manage own trainings"
on public.trainings for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users manage own exercises" on public.exercises;
create policy "Users manage own exercises"
on public.exercises for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users manage own results" on public.results;
create policy "Users manage own results"
on public.results for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users manage own daily completions" on public.daily_completions;
create policy "Users manage own daily completions"
on public.daily_completions for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
